//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatThue
    {
        public ChiTietDatThue()
        {
        }

        public ChiTietDatThue(int iD, string maXe, string ngayThue, string ngayTra)
        {
            ID = iD;
            MaXe = maXe;
            NgayThue = ngayThue;
            NgayTra = ngayTra;
        }

        public int ID { get; set; }
        public string MaXe { get; set; }
        public string NgayThue { get; set; }
        public string NgayTra { get; set; }
    }
}
