//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachCacTaiKhoanKhachHang
    {
        public DanhSachCacTaiKhoanKhachHang()
        {
        }

        public DanhSachCacTaiKhoanKhachHang(string hoVaTenKhachHang, string cMNDKhachHang, string soDienThoaiKhachHang, string diaChiKhachHang)
        {
            HoVaTenKhachHang = hoVaTenKhachHang;
            CMNDKhachHang = cMNDKhachHang;
            SoDienThoaiKhachHang = soDienThoaiKhachHang;
            DiaChiKhachHang = diaChiKhachHang;
        }

        public DanhSachCacTaiKhoanKhachHang(string hoVaTenKhachHang, string cMNDKhachHang, string soDienThoaiKhachHang, 
            string diaChiKhachHang, string tenDangNhap, string matKhau) : this(hoVaTenKhachHang, cMNDKhachHang, soDienThoaiKhachHang, 
                diaChiKhachHang)
        {
            TenDangNhap = tenDangNhap;
            MatKhau = matKhau;
        }

        public string HoVaTenKhachHang { get; set; }
        public string CMNDKhachHang { get; set; }
        public string SoDienThoaiKhachHang { get; set; }
        public string DiaChiKhachHang { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
    }
}
