//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachXeHienTai
    {
        public DanhSachXeHienTai()
        {
        }

        public DanhSachXeHienTai(string loaiXe, string hangXe, string maXe, string tenXe, int giaThue)
        {
            LoaiXe = loaiXe;
            HangXe = hangXe;
            MaXe = maXe;
            TenXe = tenXe;
            GiaThue = giaThue;
        }

        public DanhSachXeHienTai(string loaiXe, string hangXe, string maXe, string tenXe, int giaThue, int soChuyen, double danhGia)
        {
            LoaiXe = loaiXe;
            HangXe = hangXe;
            MaXe = maXe;
            TenXe = tenXe;
            GiaThue = giaThue;
            SoChuyen = soChuyen;
            DanhGia = danhGia;
        }

        public string LoaiXe { get; set; }
        public string HangXe { get; set; }
        public string MaXe { get; set; }
        public string TenXe { get; set; }
        public int SoLuongConLai { get; set; }
        public int GiaThue { get; set; }
        public int SoChuyen { get; set; }
        public double DanhGia { get; set; }
    }
}
