//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachCacTaiKhoanNhanVien
    {
        public DanhSachCacTaiKhoanNhanVien()
        {
        }

        public DanhSachCacTaiKhoanNhanVien(string tenDangNhap, string matKhau)
        {
            TenDangNhap = tenDangNhap;
            MatKhau = matKhau;
        }

        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string LoaiTaiKhoan { get; set; }
    }
}
