//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuDatXe
    {
        public DoanhThuDatXe()
        {
        }

        public DoanhThuDatXe(string tenKhachHang, string cMND, string sDT, string diaChi, string loaiXe, string hangXe, string maXe, 
            string tenXe, string ngayThue, string ngayTra, string diaDiemDon, string vatDeLai, int tienThueTaiXe, int tongTien)
        {
            TenKhachHang = tenKhachHang;
            CMND = cMND;
            SDT = sDT;
            DiaChi = diaChi;
            LoaiXe = loaiXe;
            HangXe = hangXe;
            MaXe = maXe;
            TenXe = tenXe;
            NgayThue = ngayThue;
            NgayTra = ngayTra;
            DiaDiemDon = diaDiemDon;
            VatDeLai = vatDeLai;
            TienThueTaiXe = tienThueTaiXe;
            TongTien = tongTien;
        }

        public DoanhThuDatXe(int iD, string tenKhachHang, string cMND, string sDT, string diaChi, string loaiXe, string hangXe, 
            string maXe, string tenXe, string ngayThue, string ngayTra, string diaDiemDon, string vatDeLai, int tienThueTaiXe, int tongTien)
        {
            ID = iD;
            TenKhachHang = tenKhachHang;
            CMND = cMND;
            SDT = sDT;
            DiaChi = diaChi;
            LoaiXe = loaiXe;
            HangXe = hangXe;
            MaXe = maXe;
            TenXe = tenXe;
            NgayThue = ngayThue;
            NgayTra = ngayTra;
            DiaDiemDon = diaDiemDon;
            VatDeLai = vatDeLai;
            TienThueTaiXe = tienThueTaiXe;
            TongTien = tongTien;
        }

        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string DiaChi { get; set; }
        public string LoaiXe { get; set; }
        public string HangXe { get; set; }
        public string MaXe { get; set; }
        public string TenXe { get; set; }
        public string NgayThue { get; set; }
        public string NgayTra { get; set; }
        public string DiaDiemDon { get; set; }
        public string VatDeLai { get; set; }
        public int TienThueTaiXe { get; set; }
        public int TongTien { get; set; }
    }
}
