//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuThucTe
    {
        public DoanhThuThucTe()
        {
        }

        public DoanhThuThucTe(int iD, string tenKhachHang, string cMND, string sDT, string ngayThanhToan, int tongTien)
        {
            ID = iD;
            TenKhachHang = tenKhachHang;
            CMND = cMND;
            SDT = sDT;
            NgayThanhToan = ngayThanhToan;
            TongTien = tongTien;
        }

        public int ID { get; set; }
        public string TenKhachHang { get; set; }
        public string CMND { get; set; }
        public string SDT { get; set; }
        public string NgayThanhToan { get; set; }
        public int TongTien { get; set; }
    }
}
