//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuNam
    {
        public DoanhThuNam()
        {
        }

        public DoanhThuNam(string thang, int tongTien)
        {
            Thang = thang;
            TongTien = tongTien;
        }

        public string Thang { get; set; }
        public int TongTien { get; set; }
    }
}
