//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoanhThuThang
    {
        public DoanhThuThang()
        {
        }

        public DoanhThuThang(string ngay, int tongTien)
        {
            Ngay = ngay;
            TongTien = tongTien;
        }

        public string Ngay { get; set; }
        public int TongTien { get; set; }
    }
}
