//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaGiamGia
    {
        public MaGiamGia()
        {
        }

        public MaGiamGia(string code, string hSD, string chiTietGiam)
        {
            Code = code;
            HSD = hSD;
            ChiTietGiam = chiTietGiam;
        }

        public string Code { get; set; }
        public string HSD { get; set; }
        public string ChiTietGiam { get; set; }
    }
}
