//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDoAn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuaDoAnEntityDFContext : DbContext
    {
        public SuaDoAnEntityDFContext()
            : base("name=SuaDoAnEntityDFContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDatThue> ChiTietDatThues { get; set; }
        public virtual DbSet<DanhSachCacTaiKhoanKhachHang> DanhSachCacTaiKhoanKhachHangs { get; set; }
        public virtual DbSet<DanhSachCacTaiKhoanNhanVien> DanhSachCacTaiKhoanNhanViens { get; set; }
        public virtual DbSet<DanhSachXeHienTai> DanhSachXeHienTais { get; set; }
        public virtual DbSet<DoanhThuDatXe> DoanhThuDatXes { get; set; }
        public virtual DbSet<DoanhThuNam> DoanhThuNams { get; set; }
        public virtual DbSet<DoanhThuThang> DoanhThuThangs { get; set; }
        public virtual DbSet<DoanhThuThucTe> DoanhThuThucTes { get; set; }
        public virtual DbSet<DoanhThuThueXe> DoanhThuThueXes { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<MaGiamGia> MaGiamGias { get; set; }
    }
}
